<a href="https://colab.research.google.com/github/VEOjiwon/Introduction-of-Machine-Learning/blob/main/%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80/%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 선형 회귀 ( Linear Regression )

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)


In [ ]:
#변수 선언
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [ ]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [ ]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [ ]:
# 가중치와 편향의 초기화

W = torch.zeros(1, requires_grad=True)

print(W)

b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [ ]:
# 가설 세우기

hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [ ]:
# 비용함수 선언하기

cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [ ]:
# 경사 하강법 구현

optimizer = optim.SGD([W,b], lr=0.01)

optimizer.zero_grad()
cost.backward()
optimizer.step()

In [ ]:
# 전체 코드
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))
        print(hypothesis)

Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)
Epoch  100/1999 W: 1.746, b: 0.578 Cost: 0.048171
tensor([[2.3245],
        [4.0696],
        [5.8147]], grad_fn=<AddBackward0>)
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
tensor([[2.2551],
        [4.0548],
        [5.8544]], grad_fn=<AddBackward0>)
Epoch  300/1999 W: 1.843, b: 0.357 Cost: 0.018394
tensor([[2.2006],
        [4.0430],
        [5.8855]], grad_fn=<AddBackward0>)
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
tensor([[2.1577],
        [4.0338],
        [5.9100]], grad_fn=<AddBackward0>)
Epoch  500/1999 W: 1.903, b: 0.221 Cost: 0.007024
tensor([[2.1239],
        [4.0266],
        [5.9293]], grad_fn=<AddBackward0>)
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
tensor([[2.0974],
        [4.0209],
        [5.9444]], grad_fn=<AddBackward0>)
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002682
tensor([[2.0766],
        [4.0164],
        [5.9563]], gra